### ISSUE TITLE
The migration file publishing can be steamlined

### ISSUE THREAD

**Issue by amitavroy** [listbees/vrm#3]
The logic in the service provider to publish the migration files is unnecessary complicated. There is a very simple way of doing it which I did in one of my packages which I am working on. You can check this out and let me know if you want me to do that as part of a PR

(Reference code: https://github.com/amitavdevzone/foundation/blob/master/src/FoundationServiceProvider.php)

<img width="786" alt="screen shot 2017-03-11 at 10 13 53 pm" src="https://cloud.githubusercontent.com/assets/1438890/23825017/2921533e-06a8-11e7-8648-d3e3aac77074.png">

**Comment by kunaldodiya** [comment]
Great, Thanx.. let me fix this :)
